server:
  port: 80
  servlet:
    session:
      timeout: 86400

spring:
  datasource:
    tomcat:
      min-evictable-idle-time-millis: 1800000
      num-tests-per-eviction-run: 3
      validation-query: select 1
      test-on-borrow: true
      test-while-idle: true
      test-on-return: true
#    url: jdbc:mysql://120.79.1.143:3306/db_erp_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/db_erp_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wyt1027#S
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http:
    encoding:
      force-response: true
logging:
  level:
    com: debug
#    org: debug
    web: debug

mybatis:
  mapper-locations: classpath*:com/lairun/**/mapper/*.xml